name: Get Difference
description: Checkout, fetch base branch, find changed files and filter YAML

inputs:
  base_ref:
    required: true
  file_pattern:
    required: true
  output_file:
    required: true

outputs:
  found:
    value: ${{ steps.diff_filter.outputs.found }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Get changed files of specific type
      id: diff_filter
      shell: bash
      run: |
        if git show-ref --verify --quiet refs/remotes/origin/main; then
          git diff --name-only origin/main...HEAD | grep -E '${{ inputs.file_pattern }}' > ${{ inputs.output_file }} || true
        else
          git diff --name-only HEAD | grep -E '${{ inputs.file_pattern }}' > ${{ inputs.output_file }} || true
        fi
        if [ -s ${{ inputs.output_file }} ]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

